version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  orders:
    build:
      context: ./orders
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  payments:
    build:
      context: ./payments
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      orders:
        condition: service_started
      payments:
        condition: service_started