version: '3.8'

services:
  redis:
    image: redis:8.0.2
    container_name: sssome-redis-1
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  orders:
    build:
      context: ./orders
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  payments:
    build:
      context: ./payments
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      orders:
        condition: service_started
      payments:
        condition: service_started